modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "biomediff"
version = "1.0.0"
displayName = "Configurable Difficulty"
description = "Adjusts entity attributes based on configurable difficulty"
authors = "Payangar"

[[dependencies.biomediff]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.biomediff]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "SERVER"
