modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
description = "Adjusts entity attributes based on configurable difficulty"
authors = "${mod_author}"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "SERVER"

[[dependencies.${mod_id}]]
modId = "yet_another_config_lib_v3"
type = "required"
versionRange = "[3.6.0,)"
ordering = "BEFORE"
side = "BOTH"
